name: adss
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - pip
  # （上面只放必要的 Conda 依赖；其余通过 pip 安装，见下）
  - ca-certificates
  - openssl
  - sqlite
  - tk
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-xorgproto
  - zlib
  - xz
  - ncurses
  - libffi
  - libuuid
  - libxcb
  - libgcc-ng
  - libstdcxx-ng
  - libgomp
  - ld_impl_linux-64
  - _openmp_mutex
  - _libgcc_mutex
  - wheel
  # ---- pip packages from your env ----
  - pip:
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - argparse==1.4.0
      - args==0.1.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - braceexpand==0.1.7
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - clint==0.5.1
      - clip==1.0
      - cmake==4.0.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.0.0
      - diffusers==0.24.0
      - dill==0.3.8
      - einops==0.8.0
      - exceptiongroup==1.3.0
      - fairscale==0.4.13
      - filelock==3.13.1
      - fonttools==4.59.2
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - hf-xet==1.1.9
      - hpsv2==1.2.0
      - huggingface-hub==0.23.4
      - idna==3.4
      - image-reward==1.5
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - jinja2==3.1.4
      - kiwisolver==1.4.9
      - lit==15.0.7
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - networkx==3.3
      - ninja==1.13.0
      - numpy==1.26.4
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.11.0.86
      - packaging==25.0
      - pandas==2.2.2
      - pillow==11.3.0
      - pip==25.2
      - pluggy==1.6.0
      - propcache==0.3.2
      - protobuf==3.20.3
      - psutil==7.0.0
      - pyarrow==17.0.0
      - pyparsing==3.2.3
      - pytest==7.2.0
      - pytest-split==0.8.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.5
      - safetensors==0.6.2
      - scipy==1.11.4
      - sentencepiece==0.2.0
      - setuptools==80.9.0
      - six==1.17.0
      - sympy==1.13.3
      - timm==1.0.19
      - tokenizers==0.19.1
      - tomli==2.2.1
      - torch==2.0.1+cu118
      - torchsde==0.2.6
      - torchvision==0.15.2+cu118
      - tqdm==4.67.1
      - trampoline==0.1.2
      - transformers==4.41.0
      - triton==2.0.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==1.26.13
      - wcwidth==0.2.13
      - webdataset==1.0.2
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
